### ISSUE TITLE
The display of Japanese numerical words is incorrect

### ISSUE THREAD

**Issue by 99MengXin** [jzohrab/lute#13]
**Description**

The display of Japanese numerical words is incorrect.

**To Reproduce**

Steps to reproduce the behavior, e.g.:

1. Go to `Creat New Text`
2. Copy and paste below text.
```
言葉一つで傷つくような
ヤワな私を捧げたい今
二度と訪れない季節が
```
3. Click `Save`

**Screenshots**

<img width="301" alt="2023-03-17_09 36 37" src="https://user-images.githubusercontent.com/51739513/225844160-919cb1d8-9733-4ea7-81ef-3fc9ace5238a.png">

I checked with MeCab in terminal, it can recognize numerical words very well.

<img width="578" alt="截圖 2023-03-17 15 50 11" src="https://user-images.githubusercontent.com/51739513/225844713-9bc22b76-166f-4618-87fe-2a99146f4837.png">

**Extra software info, if not already included in the Description:**

- OS (e.g., iOS, windows): macOS
- Browser (e.g., chrome, safari): brave
- Web server (e.g., regular apache/php, MAMP, XAMP...): Symfony Server
- Version (git commit): 1.1.5

**Comment by jzohrab** [comment]
I can't reproduce this.  Same git commit, same text, on save the parsing looks like this:

![image](https://user-images.githubusercontent.com/1637133/225949998-3d829bfc-54e3-4f74-b641-3684e1b687c3.png)

Did you have Japanese terms already saved from a prior text?

**Comment by jzohrab** [comment]
Can you run the same thing again with the following command?

`mecab "-F %m\t%t\t%h\n -U %m\t%t\t%h\n -E EOP\t3\t7\n"`

eg for me, this gives the following (snipped):

```
$ mecab "-F %m\t%t\t%h\n -U %m\t%t\t%h\n -E EOP\t3\t7\n"
言葉一つで傷つくような
ヤワな私を捧げたい今
二度と訪れない季節が 言葉	2	38
 -U 言葉	2	38
 -E EOP	3	7
 一つ	8	38
 -U 一つ	8	38
 -E EOP	3	7
 で	6	13
 -U で	6	13
etc.
```

**Comment by 99MengXin** [comment]
@jzohrab FYI

```
mecab "-F %m\t%t\t%h\n -U %m\t%t\t%h\n -E EOP\t3\t7\n"
言葉一つで傷つくような
ヤワな私を捧げたい今
二度と訪れない季節が 言葉	2	39
 -U 言葉	2	39
 -E EOP	3	7
 一	4	36
 -U 一	4	36
 -E EOP	3	7
 つ	6	20
 -U つ	6	20
 -E EOP	3	7
 で	6	5
 -U で	6	5
 -E EOP	3	7
 傷つく	2	22
 -U 傷つく	2	22
 -E EOP	3	7
 ような	6	9
 -U ような	6	9
 -E EOP	3	7
EOS
 ヤワ	7	35
 -U ヤワ	7	35
 -E EOP	3	7
 な	6	39
 -U な	6	39
 -E EOP	3	7
 私	2	39
 -U 私	2	39
 -E EOP	3	7
 を	6	5
 -U を	6	5
 -E EOP	3	7
 捧げ	2	22
 -U 捧げ	2	22
 -E EOP	3	7
 たい	6	15
 -U たい	6	15
 -E EOP	3	7
 今	2	34
 -U 今	2	34
 -E EOP	3	7
EOS
```

**Comment by 99MengXin** [comment]
Hi @jzohrab 

I found the package `mecab-ipadic-utf8` of `MeCab` was missing or never installed, I am not sure...
It's normal now after installation currently.

Solution for Debian/Ubuntu/Raspberry Pi OS:

```
sudo apt update && sudo apt upgrade -y && sudo apt autoremove -y
sudo apt install -y mecab mecab-ipadic-utf8
```

**Comment by jzohrab** [comment]
Already documented on wiki at https://github.com/jzohrab/lute/wiki/Japanese-Support.  Thanks!
