### ISSUE TITLE
Giving users the option to choose whether or not to use the book feature

### ISSUE THREAD

**Issue by 99MengXin** [jzohrab/lute#14]
**Is your feature request related to a problem? Please describe.**

I suggest giving users the option to choose whether or not to use the `book` feature when they import text. eg. lyric

**Describe the solution you'd like**

The default setting could be to not use the `book` feature, and users can click on ⚡️ to activate it when they decide to do so.

**Describe alternatives you've considered**

When importing a TXT file, the input will be treated as a `book` feature. When importing via copy and paste in the Text column, the input will be treated as a single page but keep the ⚡️ option.

**Additional context**

There is a dirty way currently. Create an one line text first then update the text, you will see the whole text and ⚡ for `book` feature if you want to do so️ in the future.

**Comment by jzohrab** [comment]
I'm going to close this one.  It's not a bad idea, but I feel it's such a niche request that it's not worth doing, at least at the moment.  Can revisit (and reopen) if this is requested again in the future.  Cheers! jz
