### ISSUE TITLE
Fatal error: Invalid default value for 'UpdatedDate' - On Lute installation

### ISSUE THREAD

**Issue by HugoFara** [jzohrab/lute#2]
**Invalid timestamp**

Hi Jeff! I'm trying to install Lute with a LAMP server, but I ran into a fatal error. Basically, the app crashes while displaying ``File 20221221_233742_add_textstatscache_timestamps.sql exception: Invalid default value for 'UpdatedDate' Quitting``.

The file is located at ``./db/migrations/20221221_233742_add_textstatscache_timestamps.sql``. I have been trying multiple different timestamps as ``0000-00-00 00:00:00`` or ``0`` without any change. The annoying thing is that it also make the tests crash.

- Ubuntu
- LAMP
- MySQL: 8.0.31
-  Apache/2.4.52

EDIT: skipping this instructions was enough, as it is a fresh DB install, I don't need the migration.

**Comment by jzohrab** [comment]
Thanks HF for the note!  Hopefully this is a quick fix, looking into it.

You still need the migration, even on a fresh db install.  That migration hasn't been made permanent in the baseline db.

**Comment by jzohrab** [comment]
I believe I'm off by 1 second.  Per [this SO post](https://stackoverflow.com/a/37420863/1695066) which points to [the docs](https://dev.mysql.com/doc/refman/8.0/en/datetime.html):

> the range for TIMESTAMP values is '1970-01-01 00:00:01.000000' to '2038-01-19 03:14:07.999999'

That migration has 

```
alter table textstatscache
add column UpdatedDate timestamp default '1970-01-01 00:00:00'
after TxID;

alter table textstatscache
add column LastParse timestamp default '1970-01-01 00:00:00'
after TxID;
```

Fixing that migration in master.

**Comment by jzohrab** [comment]
I changed these columns to be NULLable, which makes more sense, rather than putting in a dubious date.

Fixed in master, but I'll leave this issue open until a) @HugoFara gets a chance to test it out, and b) I've created a new release with this hotfix.

Thanks Hugo!  (I'll see about setting up a GitHub action to test this in an Ubuntu environment, right now I'm just testing on my Mac, which isn't good enough.)

**Comment by jzohrab** [comment]
GitHub CI set up, and _would have caught this issue_ :-(  Alas.  Issue is fixed in master as well.

**Comment by HugoFara** [comment]
Hi! I pulled your latest version today, and the issue does not longer appear so well done. Ironically enough, you signaled me this exact same bug for LWT last month ([hugofara/lwt#78](https://github.com/HugoFara/lwt/issues/78)) :laughing: 

Have a nice day!
