### ISSUE TITLE
Backup files with timestamp and rolling settings

### ISSUE THREAD

**Issue by 99MengXin** [jzohrab/lute#25]
**Is your feature request related to a problem? Please describe.**

In the V2 beta version, there is currently only `one` backup file available, and the manual files are also rolled by the automatic backup.

**Describe the solution you'd like**

It would be helpful to create backup files with timestamps and keep all manual backups because there are instances where people prefer manual backups. It would also be great if those backup files could be managed in Lute.

Additionally, we might consider keeping 2-3 auto backup files, and include one file from the end of the previous month.

**Describe alternatives you've considered**

Add timestamps feature and move backup files manually.

**Additional context**

![2023-04-17_15 29 26](https://user-images.githubusercontent.com/51739513/232640232-4910810e-d75b-45c7-aeb0-77d387a75312.png)

**Comment by jzohrab** [comment]
This is fixed in `develop`, thanks.

I wasn't sure about the concept for "manual", but hey, why not.  "Manual" backups (where you click the link) are prefixed by "manual_" in the filename.  Automatic ones aren't prefixed, and are governed by the "BACKUP_COUNT" .env file param (wiki also updated).

For example:

```
MacBook-Air-2:lute_dev jeff$ ls -1 zz_backup/
lute_backup_2023-04-19_204452.db.gz     # I only have 5 "automatic" backups
lute_backup_2023-04-19_204512.db.gz
lute_backup_2023-04-19_204519.db.gz
lute_backup_2023-04-19_204547.db.gz
lute_backup_2023-04-19_204604.db.gz
manual_lute_backup_2023-04-19_204132.db.gz     # I'll have as many of these as I decide to keep
manual_lute_backup_2023-04-19_204204.db.gz
manual_lute_backup_2023-04-19_204652.db.gz
userimages_backup    # There is only one folder of images, ever.  :-)
```
