### ISSUE TITLE
Error when add text to Lute

### ISSUE THREAD

**Issue by hieutran-coder** [jzohrab/lute#4]
**Description**

Brief description of bug. Include copy-paste of error message details, or table of error data, if available.
<img width="1383" alt="Screen Shot 2023-02-15 at 22 43 58" src="https://user-images.githubusercontent.com/57060034/219077321-c2ce6353-8c71-4299-bad8-e270b6e37066.png">

**To Reproduce**

Steps to reproduce the behavior, e.g.:

2. Click on '...'
3. Scroll down to '...'

**Screenshots**

If it will be helpful, add screenshots.

**Extra software info, if not already included in the Description:**

- OS (e.g., iOS, windows):
- Browser (e.g., chrome, safari):
- Web server (e.g., regular apache/php, MAMP, XAMP...):
- Version (git commit):

**Comment by hieutran-coder** [comment]
"Right click libphp.so, and click "Show original." Copy that file."
In file libphp.so I don't see "Show original" so I don't follow this steps. HIC

**Comment by jzohrab** [comment]
Very odd ... the only way that could occur (I think!) is if a language wasn't selected when you created the text, but the UI should have prevented posting if the text wasn't selected:

![image](https://user-images.githubusercontent.com/1637133/219122416-e0aa0052-729c-4996-adc6-af944d580da7.png)

If this happens again, please show the page just before you clicked "Save".  Thanks @hieutran-coder! jz

**Comment by hieutran-coder** [comment]
Yes, thank for your reply
