### ISSUE TITLE
Error when starting docker

### ISSUE THREAD

**Issue by rococtz** [jzohrab/lute#42]
Just wondering if anyone could help me run this project with Docker.

Steps that I took:
* clone the repo
* cd into the repo using CMD (Windows 11)
* ran the command `docker compose build` (as per instructions)
* I get this:
```
c:\code\lute>docker compose build
time="2023-06-25T10:54:29+12:00" level=warning msg="The \"BACKUP_HOST_DIR\" variable is not set. Defaulting to a blank string."
1 error(s) decoding:

error decoding 'volumes[1]': invalid spec: :/lute/backup: empty section between colons
```

**Comment by jzohrab** [comment]
Hi there @rococtz -- you've skipped a few steps for the setup. :-)  Cloning as-is won't get you everything, and you need to configure some stuff too.  Check out https://github.com/jzohrab/lute/wiki/Installation-overview, and drop into the Discord (linked on the wiki footer) if you're still stuck.  Cheers!

(Leaving issue open for a bit, until you acknowledge. jz)
