### ISSUE TITLE
Raspberry Pi installation fails

### ISSUE THREAD

**Issue by jzohrab** [jzohrab/lute#54]
I believe that @99MengXin already has Lute running with Docker on the Rasp Pi - in the Discord "install" channel ecurp_forp is having massive trouble getting started ... and I'm not sure what's wrong.

I have _no idea_ what the issue is, and can't debug it or suggest changes, so maybe try setting up a Vagrant Box with a Rasp Pi OS, put Docker in there, install Lute in there, run it ... and watch the world explode.  (Try using Vagrant box w/ Docker inside, and run Lute within Docker within Vagrant)

- https://stackoverflow.com/questions/47415732/best-way-to-install-docker-on-vagrant
- https://app.vagrantup.com/henryfbp/boxes/raspberry-pi-desktop

and the rest should be ... pretty straightforward.  :-/  Not.

**Comment by 99MengXin** [comment]
# Raspberry Pi

I love this useful and cheap tool.

## Platform

```
hostnamectl
```

Operating System: Debian GNU/Linux 11 (bullseye)
Kernel: Linux 6.1.21-v8+
Architecture: arm64

## Docker Installation

You need docker first, and it's super easy. [Install Docker Engine on Debian | Docker Documentation](https://docs.docker.com/engine/install/debian/)

```
curl -fsSL https://get.docker.com -o get-docker.sh
sudo sh get-docker.sh
```
## Lute Installation

Follow step by step, and you will not get lost. 🙂

Step 1
- Go back your home

```
cd
```

Step 2
- Create the folders we need

```
mkdir ./Containers/lute/lute_2.0.7 -p
mkdir ./Containers/lute/LuteBackup -p
```

Step 3
- Go to the folder you just created

```
cd ./Containers/lute/lute_2.0.7
```

Step 4
- Download lute from GitHub

```
wget https://github.com/jzohrab/lute/releases/download/v2.0.7/lute_release.zip
```

Step 5
- Unzip the file

```
unzip lute_release.zip
```

Step 6
- Remove the zip file

```
rm lute_release.zip
```

Step 7
- Go back your home

```
cd
```

Step 8
- Go to your backup folder

```
cd ./Containers/lute/LuteBackup
```

Step 9
- Check and copy your backup direction

```
pwd
```

Step 10
- Go back your home

```
cd
```

Step 11
- Go back to lute folder

```
cd ./Containers/lute/lute_2.0.7
```

Step 12
- Copy `.env` file for lute

```
cp .env.example.docker .env
```

Step 13
- Open `.env` with nano editor

```
nano .env
```

Step 14
- In Line 6, put what you got at `Step 9`
- If your username is `pi`, it will be `/home/pi/Containers/lute/LuteBackup`

```
BACKUP_HOST_DIR=/home/pi/Containers/lute/LuteBackup
```

Step 15
- In Line 7, amend the `false` to `true`

```
BACKUP_ENABLED=true
```

Step 16
- In line 16 and 17, amend the `yourusername` and `yourpassword` to what ever you like, e.g. `lute`

```
LOGIN_USERNAME=lute
LOGIN_PASSWORD=lute
```

Step 17
- Open `security.yaml` with nano editor

```
nano ./config/packages/security.yaml
```

Step 18
- In Line 18 and 23,  amend `false` to `true`

```
security: true
```

Step 19
- Copy your data from previous version, e.g. lute 2.0.5
- If you are new in here, skip this step

```
cp ../lute_2.0.5/data/lute.db ./data/lute.db
```

Step 20
- Build the image

```
docker compose build
```

Step 21
- Up the container

```
docker compose up -d
```

Step 22
- Open your favorite browser and go to `[Your Pi's IP]:8000`

Step 23
- Enjoy and Cheers 🎉

**Comment by jzohrab** [comment]
This is going on the wiki when I get permission to add it! :-)  Thank you for the detail!

**Comment by jzohrab** [comment]
I've added this to the wiki.  Rather than keep this open, will wait for feedback from ecurb_forp in discord, he/she prompted this initial ticket.
