### ISSUE TITLE
Creating a registry for the app image in docker hub is possible?

### ISSUE THREAD

**Issue by DiogoJorge1401** [jzohrab/lute#59]
I think creating a registry in docker hub would make it easier to install and update the app as new versions are released. 

What do you guys thinks about it? Is it hard to manage?

**Comment by jzohrab** [comment]
Hi thanks for the issue.  This is the right direction for Lute to go, it would be very good for users.  As far as I can tell, the only issue blocking this is #20 - I'm not sure what is needed to ensure that images work on all architectures.  I only have a mac, and don't have enough experience with this to ensure I'd do it correctly.  If you (or anyone else!) has some thoughts about this, input would be super.

(There would also be some minimal documentation required for the .env file and the docker-compose, but that's trivial.)

**Comment by jzohrab** [comment]
Lute v3 has this, https://hub.docker.com/repository/docker/jzohrab/lute3/general

Good enough for now, I may move it elsewhere, like into an org.
