### ISSUE TITLE
Hover window sometimes gets stuck

### ISSUE THREAD

**Issue by Mycheze** [jzohrab/lute#73]
**Description**

Sometimes, when opening the "side information," the hover window gets stuck open and needs a reload.

**To Reproduce**

Steps to reproduce the behavior, e.g.:

*Unsure of exactly how to cause it*
1. Click on a word to open the side window
2. Have the look-up take a moment to load
3. Move your cursor so that there's an overlap between the hover box and the side panel
4. Hover box gets stuck open

**Screenshots**

![lutebug2](https://github.com/jzohrab/lute/assets/71797685/bc5fd4be-1e19-4045-acd9-87fcd6a2e20e)
![lutebug1](https://github.com/jzohrab/lute/assets/71797685/93008547-ceba-4adf-8367-23ff7e20baea)

**Extra software info, if not already included in the Description:**

- OS (e.g., iOS, windows): Pop!_OS
- Browser (e.g., chrome, safari): Chromium
- Web server (e.g., regular apache/php, MAMP, XAMP...): Idk I installed through Docker
- Version (git commit): v2.0.13

**Comment by jzohrab** [comment]
Happens to me too, I've been too lazy to fix it!  Ctrl+R "fixes" it.  Absolutely no idea why it sometimes hangs around ... thank you for the note about the overlap though, that might be a good clue.

**Comment by jzohrab** [comment]
Easier reproduce: hover on something, and then only use keyboard to navigate and save.  e.g.:

Hover on predefined word:

> <img width="214" alt="image" src="https://github.com/jzohrab/lute/assets/1637133/6981e84c-2e9a-4033-9af9-58badfd04ebb">

Click it, and the form opens up in the right frame:

> <img width="935" alt="image" src="https://github.com/jzohrab/lute/assets/1637133/cb223c23-e349-4357-96c5-804b90ef8845">

Hit tab-tab-tab until the focus is on, say, the status, move the status with arrow right or left, and hit return.  Form is saved, and the popup remains:

> <img width="377" alt="image" src="https://github.com/jzohrab/lute/assets/1637133/05c085c1-bf52-4168-92bc-95995a1e7bdb">

**Comment by jzohrab** [comment]
Fixed in the develop branch -- or at least, it should be.  It is fixed for my case (using keyboard nav only), and am assuming that it will be fixed for yours as well.

e.g., click on elephant, hover info shows:

> <img width="210" alt="image" src="https://github.com/jzohrab/lute/assets/1637133/618b2492-b6b7-4084-908c-51807ed9aafa">

Using only keyboard navigation (tab), change the translation, change the status, and hit Return while in the status.  Popup is immed. updated and will disappear when cursor is moved:

> <img width="180" alt="image" src="https://github.com/jzohrab/lute/assets/1637133/afb7f06c-0b91-4dca-9f58-01ce24a618df">

Merged into the `develop` branch, will launch soon.

**Comment by jzohrab** [comment]
Fixed in v2.1.2 just launched.
