### ISSUE TITLE
Image can't be selected if the "border" pushes it to a new line

### ISSUE THREAD

**Issue by Mycheze** [jzohrab/lute#75]
**Description**

Kind of a funny little bug that doesn't really matter... But when you're adding an image, if the image you want to add is *right* against the border of the screen, hovering over it will add the highlight, pushing it down a line, which means it won't be under your cursor anymore. And moving to its new spot puts it back in the original place.

**To Reproduce**

Steps to reproduce the behavior, e.g.:

1. Add image
2. Hover over an image that moves to the next line
3. Realize you can't add it

**Screenshots**

DMed the video file to jz.

**Extra software info, if not already included in the Description:**

- OS (e.g., iOS, windows): Pop!_OS
- Browser (e.g., chrome, safari): Chromium
- Web server (e.g., regular apache/php, MAMP, XAMP...): idk
- Version (git commit): v2.0.13

**Comment by jzohrab** [comment]
Ha yeah, this one is silly, should have fixed it.  I _think_ it's trivial.

**Comment by jzohrab** [comment]
Fixed in develop branch, to be in next launch.

**Comment by jzohrab** [comment]
In v2.1.3.
